// Fallback dataset used until Supabase is configured. Mirrors the seed in supabase/schema.sql
// so the site looks alive on first launch and during local dev without env vars.

import type { Product, ArchiveItem, Artisan, BlogPost } from "./supabase/types";
import { productImages, archiveImages } from "./images";

const now = new Date().toISOString();

export const fallbackProducts: Product[] = [
  {
    id: "fb-1",
    slug: "melhfa-aurassienne",
    category: "heritage",
    title: {
      ar: "الملحفة الأوراسية الأصيلة",
      fr: "Melhfa aurassienne authentique",
      en: "Authentic Aurès Melhfa",
    },
    short_description: {
      ar: "ملحفة منسوجة يدويًا بألوان الأوراس التقليدية",
      fr: "Melhfa tissée à la main aux couleurs traditionnelles des Aurès",
      en: "Hand-woven melhfa in traditional Aurès colors",
    },
    story: {
      ar: "تُنسج الملحفة على نول تقليدي خلال عدة أسابيع، باستخدام صباغة طبيعية مستخرجة من نباتات المنطقة.",
      fr: "La melhfa est tissée sur un métier traditionnel pendant plusieurs semaines, avec des teintures naturelles extraites des plantes de la région.",
      en: "The melhfa is woven on a traditional loom over several weeks, with natural dyes from regional plants.",
    },
    symbolism: {
      ar: "الأحمر يرمز للحياة والخصوبة، والأسود للأرض والثبات.",
      fr: "Le rouge symbolise la vie et la fertilité, le noir la terre et la stabilité.",
      en: "Red symbolizes life and fertility, black the earth and stability.",
    },
    occasion: {
      ar: "الأعراس والمناسبات الكبرى",
      fr: "Mariages et grandes occasions",
      en: "Weddings and major celebrations",
    },
    artisan_name: "فاطمة الزهراء",
    price_dzd: 18500,
    sizes: ["S", "M", "L", "XL"],
    images: [productImages.kaftan_styled, productImages.embroidered_garment, productImages.textile_stack],
    in_stock: true,
    featured: true,
    created_at: now,
  },
  {
    id: "fb-2",
    slug: "qachabia-moderne",
    category: "modern",
    title: {
      ar: "قشابية عصرية مستوحاة",
      fr: "Qachabia contemporaine",
      en: "Contemporary Qachabia",
    },
    short_description: {
      ar: "إعادة تأويل عصرية للقشابية التقليدية بقماش خفيف",
      fr: "Réinterprétation moderne de la qachabia avec un tissu léger",
      en: "Modern reinterpretation in lightweight fabric",
    },
    story: {
      ar: "يعيد هذا التصميم اكتشاف القشابية بقصّة معاصرة، مع الحفاظ على التفاصيل الزخرفية الأصلية.",
      fr: "Ce design redécouvre la qachabia avec une coupe contemporaine, tout en préservant les détails ornementaux originaux.",
      en: "This design reimagines the qachabia with a contemporary cut while preserving the original ornamental details.",
    },
    symbolism: {
      ar: "الزخارف الهندسية تستلهم من الفن الشاوي",
      fr: "Les motifs géométriques s'inspirent de l'art chaoui",
      en: "Geometric motifs draw from Chaoui art",
    },
    occasion: {
      ar: "الاستعمال اليومي والمناسبات شبه الرسمية",
      fr: "Usage quotidien et occasions semi-formelles",
      en: "Daily wear and semi-formal occasions",
    },
    artisan_name: "خديجة بن صالح",
    price_dzd: 9800,
    sizes: ["S", "M", "L"],
    images: [productImages.kaftan_detail, productImages.embroidery_linen, productImages.embroidery_threadwork],
    in_stock: true,
    featured: true,
    created_at: now,
  },
  {
    id: "fb-3",
    slug: "khit-rrouh-pendant",
    category: "accessories",
    title: {
      ar: "قلادة خيط الروح",
      fr: "Pendentif Khit Rrouh",
      en: "Khit Rrouh pendant",
    },
    short_description: {
      ar: "قلادة فضية مستوحاة من الحلي الأمازيغية",
      fr: "Pendentif en argent inspiré des bijoux amazighs",
      en: "Silver pendant inspired by Amazigh jewelry",
    },
    story: {
      ar: "تُنحت بالطرق التقليدي وتُزيّن بنقوش رمزية تحمي صاحبتها.",
      fr: "Forgé à la main avec des motifs symboliques protecteurs.",
      en: "Hand-forged with symbolic protective motifs.",
    },
    symbolism: {
      ar: "الرموز الهندسية رموز حماية وحياة",
      fr: "Les symboles géométriques évoquent protection et vie",
      en: "The geometric symbols evoke protection and life",
    },
    occasion: {
      ar: "هدية رمزية، مناسبات الزواج والاحتفال",
      fr: "Cadeau symbolique, mariages et célébrations",
      en: "A symbolic gift, weddings and celebrations",
    },
    artisan_name: "يمينة العوراسي",
    price_dzd: 4200,
    sizes: null,
    images: [productImages.silver_pendant_malachite, productImages.silver_necklace],
    in_stock: true,
    featured: false,
    created_at: now,
  },
  {
    id: "fb-4",
    slug: "khimar-chaoui-embroidered",
    category: "accessories",
    title: {
      ar: "خمار شاوي مطرز",
      fr: "Khimar chaoui brodé",
      en: "Embroidered Chaoui Khimar",
    },
    short_description: {
      ar: "خمار شاوي تقليدي مطرز بخيوط ملونة على قماش فاخر، يجمع بين الأناقة والتراث الأصيل.",
      fr: "Khimar chaoui traditionnel brodé de fils colorés sur un tissu raffiné, alliant élégance et patrimoine authentique.",
      en: "Traditional Chaoui khimar embroidered with colored threads on premium fabric, blending elegance with authentic heritage.",
    },
    story: {
      ar: "تصميم خفيف ومريح يناسب الاستخدام اليومي والمناسبات. قماش فاخر مطرز يدويًا بخيوط ملونة عالية الجودة، بأبعاد 100 × 100 سم تقريبًا. يُغسل يدويًا بالماء البارد.",
      fr: "Un design léger et confortable adapté à l'usage quotidien comme aux grandes occasions. Tissu raffiné brodé à la main de fils colorés de haute qualité, dimensions d'environ 100 × 100 cm. Lavage à la main à l'eau froide.",
      en: "A light, comfortable design suited to both daily wear and special occasions. Premium fabric hand-embroidered with high-quality colored threads, about 100 × 100 cm. Hand-wash in cold water.",
    },
    symbolism: {
      ar: "تطريز شاوي أصيل بخيوط زاهية يعكس التراث الأوراسي.",
      fr: "Une broderie chaoui authentique aux fils éclatants qui reflète le patrimoine des Aurès.",
      en: "Authentic Chaoui embroidery in vivid threads that reflects the heritage of the Aurès.",
    },
    occasion: {
      ar: "الاستخدام اليومي والمناسبات",
      fr: "Usage quotidien et occasions",
      en: "Daily wear and occasions",
    },
    artisan_name: null,
    price_dzd: 2500,
    sizes: null,
    images: ["/products/10.webp"],
    in_stock: true,
    featured: true,
    created_at: now,
  },
  {
    id: "fb-5",
    slug: "hzam-chaoui-multifil",
    category: "accessories",
    title: {
      ar: "حزام شاوي متعدد الخيوط",
      fr: "Ceinture chaoui multi-fils",
      en: "Multi-thread Chaoui Belt",
    },
    short_description: {
      ar: "حزام تقليدي شاوي مصنوع يدويًا من خيوط ملونة متداخلة، يزيّن الملابس التقليدية النسائية ويضيف لمسة جمالية تراثية أصيلة.",
      fr: "Ceinture chaoui traditionnelle faite main à partir de fils colorés entrelacés, qui orne les tenues féminines traditionnelles et ajoute une touche esthétique patrimoniale authentique.",
      en: "Traditional Chaoui belt handmade from interwoven colored threads, adorning traditional women's attire with an authentic heritage touch.",
    },
    story: {
      ar: "مشغول يدويًا بإتقان من خيوط قطنية متعددة الألوان، بطول 150 سم قابل للتعديل ليلائم جميع المقاسات. يُغسل يدويًا بماء بارد.",
      fr: "Confectionnée à la main avec soin à partir de fils de coton multicolores, longueur 150 cm ajustable pour convenir à toutes les tailles. Lavage à la main à l'eau froide.",
      en: "Carefully handmade from multicolored cotton threads, 150 cm adjustable length to fit all sizes. Hand-wash in cold water.",
    },
    symbolism: {
      ar: "مزيج متناغم من الألوان التقليدية المستوحاة من التراث الشاوي.",
      fr: "Un mélange harmonieux de couleurs traditionnelles inspirées du patrimoine chaoui.",
      en: "A harmonious blend of traditional colors inspired by Chaoui heritage.",
    },
    occasion: {
      ar: "يكمّل الزيّ التقليدي في المناسبات",
      fr: "Complète la tenue traditionnelle lors des occasions",
      en: "Completes traditional attire for occasions",
    },
    artisan_name: null,
    price_dzd: 2800,
    sizes: null,
    images: ["/products/9.webp"],
    in_stock: true,
    featured: true,
    created_at: now,
  },
  {
    id: "fb-6",
    slug: "libas-chaoui-complet",
    category: "heritage",
    title: {
      ar: "لباس تقليدي شاوي كامل",
      fr: "Tenue chaoui traditionnelle complète",
      en: "Complete Traditional Chaoui Outfit",
    },
    short_description: {
      ar: "زيّ تقليدي شاوي أصيل يعكس جمال التراث الجزائري وخصوصية الثقافة الشاوية، يجمع بين الألوان الزاهية والتطريز اليدوي الفاخر والإكسسوارات التقليدية.",
      fr: "Tenue chaoui traditionnelle authentique reflétant la beauté du patrimoine algérien et la singularité de la culture chaoui, alliant couleurs vives, broderie main raffinée et accessoires traditionnels.",
      en: "Authentic traditional Chaoui outfit reflecting the beauty of Algerian heritage and the distinctiveness of Chaoui culture, combining vivid colors, fine hand embroidery and traditional accessories.",
    },
    story: {
      ar: "تصميم متكامل يجمع بين الصدرة والتطريز التقليدي، والحزام المزخرف، والأكمام الواسعة المطرزة بحواف ملونة، لتنسيق مثالي بين القطع المختلفة في جميع المناسبات. يُغسل يدويًا بالماء البارد.",
      fr: "Un ensemble complet réunissant le plastron et la broderie traditionnelle, la ceinture ornée et les manches amples brodées aux bords colorés, pour une harmonie parfaite en toutes occasions. Lavage à la main à l'eau froide.",
      en: "A complete ensemble bringing together the embroidered bodice, the ornate belt, and wide sleeves with colored trims, for perfect harmony across all occasions. Hand-wash in cold water.",
    },
    symbolism: {
      ar: "تطريز يدوي فاخر مع إكسسوارات من الفضة التقليدية يعكس أصالة الزيّ الشاوي.",
      fr: "Broderie main raffinée et accessoires en argent traditionnel reflétant l'authenticité de la tenue chaoui.",
      en: "Fine hand embroidery with traditional silver accessories reflecting the authenticity of Chaoui dress.",
    },
    occasion: {
      ar: "الأعراس والمناسبات الكبرى",
      fr: "Mariages et grandes occasions",
      en: "Weddings and major celebrations",
    },
    artisan_name: null,
    price_dzd: 18500,
    sizes: ["S", "M", "L", "XL"],
    images: ["/products/7.webp"],
    in_stock: true,
    featured: true,
    created_at: now,
  },
  {
    id: "fb-7",
    slug: "haqiba-chaoui-embroidered",
    category: "accessories",
    title: {
      ar: "حقيبة شاوية مطرزة",
      fr: "Sac chaoui brodé",
      en: "Embroidered Chaoui Bag",
    },
    short_description: {
      ar: "حقيبة يدوية مطرزة بنقوش أمازيغية وخرز فضي وشرّابات ملونة، متوفرة بعدة تصاميم.",
      fr: "Sac fait main brodé de motifs amazighs, perles argentées et pompons colorés, disponible en plusieurs modèles.",
      en: "Handmade bag embroidered with Amazigh motifs, silver beads and colorful tassels, available in several styles.",
    },
    story: {
      ar: "تُطرّز كل حقيبة يدويًا على قماش متين بنقوش هندسية تستلهم من الزرابي الأوراسية، مع زخارف فضية وشرّابات.",
      fr: "Chaque sac est brodé à la main sur un tissu résistant avec des motifs géométriques inspirés des tapis des Aurès, ornés de pièces argentées et de pompons.",
      en: "Each bag is hand-embroidered on durable fabric with geometric motifs inspired by Aurès rugs, finished with silver ornaments and tassels.",
    },
    symbolism: {
      ar: "النقوش الهندسية رموز حماية وانتماء في الثقافة الأمازيغية.",
      fr: "Les motifs géométriques sont des symboles de protection et d'appartenance dans la culture amazighe.",
      en: "The geometric motifs are symbols of protection and belonging in Amazigh culture.",
    },
    occasion: {
      ar: "الاستخدام اليومي والمناسبات",
      fr: "Usage quotidien et occasions",
      en: "Daily use and occasions",
    },
    artisan_name: null,
    price_dzd: 4500,
    sizes: null,
    images: ["/products/1.webp"],
    in_stock: true,
    featured: true,
    created_at: now,
  },
  {
    id: "fb-8",
    slug: "qilada-chaoui-silver",
    category: "accessories",
    title: {
      ar: "قلادة شاوية فضية",
      fr: "Collier chaoui en argent",
      en: "Silver Chaoui Necklace",
    },
    short_description: {
      ar: "قلادة بحجر أحمر ونقوش فضية وخرز ملوّن وقطع نقدية تقليدية، مستوحاة من الحلي الأوراسية.",
      fr: "Collier à pierre rouge, motifs argentés, perles colorées et pièces traditionnelles, inspiré des bijoux des Aurès.",
      en: "Necklace with a red stone, silver motifs, colored beads and traditional coins, inspired by Aurès jewelry.",
    },
    story: {
      ar: "تُجمع القلادة يدويًا من خرز ملوّن وقطع فضية معلّقة حول حجر مركزي أحمر يتدلّى منه زخارف.",
      fr: "Le collier est assemblé à la main à partir de perles colorées et de pièces en argent autour d'une pierre rouge centrale ornée de pendeloques.",
      en: "The necklace is hand-assembled from colored beads and hanging silver pieces around a central red stone with dangling ornaments.",
    },
    symbolism: {
      ar: "الفضة والحجر الأحمر رمزا الحماية والحياة في التقليد الأمازيغي.",
      fr: "L'argent et la pierre rouge symbolisent la protection et la vie dans la tradition amazighe.",
      en: "Silver and the red stone symbolize protection and life in Amazigh tradition.",
    },
    occasion: {
      ar: "المناسبات والأعراس وهدية رمزية",
      fr: "Occasions, mariages et cadeau symbolique",
      en: "Occasions, weddings and a symbolic gift",
    },
    artisan_name: null,
    price_dzd: 4200,
    sizes: null,
    images: ["/products/2.webp"],
    in_stock: true,
    featured: false,
    created_at: now,
  },
  {
    id: "fb-9",
    slug: "libas-chaoui-noir",
    category: "heritage",
    title: {
      ar: "لباس شاوي أسود مطرز",
      fr: "Tenue chaoui noire brodée",
      en: "Black Embroidered Chaoui Outfit",
    },
    short_description: {
      ar: "زيّ شاوي أسود كامل (خمار وفستان) مطرز بالرمز الأمازيغي وحواف بألوان التراث وشرّابات.",
      fr: "Tenue chaoui noire complète (khimar et robe) brodée du symbole amazigh, avec bordures aux couleurs du patrimoine et pompons.",
      en: "Complete black Chaoui set (khimar and dress) embroidered with the Amazigh symbol, with heritage-colored trims and tassels.",
    },
    story: {
      ar: "يجمع هذا الزيّ بين الخمار والفستان، مطرّزًا بالرمز الأمازيغي (آزا) وزخارف نجمية، مع حواف بألوان الأحمر والأصفر والأخضر وشرّابات يدوية.",
      fr: "Cette tenue réunit le khimar et la robe, brodée du symbole amazigh (Aza) et de motifs étoilés, avec des bordures rouge, jaune et vert et des pompons faits main.",
      en: "This set pairs the khimar with the dress, embroidered with the Amazigh symbol (Aza) and star motifs, with red, yellow and green trims and handmade tassels.",
    },
    symbolism: {
      ar: "الرمز الأمازيغي (آزا) يرمز للحرية والإنسان الحر.",
      fr: "Le symbole amazigh (Aza) représente la liberté et l'homme libre.",
      en: "The Amazigh symbol (Aza) represents freedom and the free person.",
    },
    occasion: {
      ar: "الأعراس والمناسبات الكبرى",
      fr: "Mariages et grandes occasions",
      en: "Weddings and major celebrations",
    },
    artisan_name: null,
    price_dzd: 16000,
    sizes: ["S", "M", "L", "XL"],
    images: ["/products/3.webp"],
    in_stock: true,
    featured: true,
    created_at: now,
  },
  {
    id: "fb-10",
    slug: "khimar-chaoui-noir",
    category: "accessories",
    title: {
      ar: "خمار شاوي أسود مطرز",
      fr: "Khimar chaoui noir brodé",
      en: "Black Embroidered Chaoui Khimar",
    },
    short_description: {
      ar: "خمار أسود مطرز بخيوط برتقالية وحمراء بنقوش هندسية دقيقة، مع شرّابات على الأطراف.",
      fr: "Khimar noir brodé de fils orange et rouge aux motifs géométriques fins, avec des pompons sur les bords.",
      en: "Black khimar embroidered with orange and red threads in fine geometric motifs, with tassels along the edges.",
    },
    story: {
      ar: "خمار خفيف من قماش أسود مطرّز يدويًا بنقوش متقاطعة دقيقة، يُنهى بشرّابات على الحواف. يُغسل يدويًا بالماء البارد.",
      fr: "Khimar léger en tissu noir brodé à la main de motifs croisés fins, fini de pompons sur les bords. Lavage à la main à l'eau froide.",
      en: "Light black-fabric khimar hand-embroidered with fine cross motifs, finished with tassels along the edges. Hand-wash in cold water.",
    },
    symbolism: {
      ar: "النقوش المتقاطعة تستلهم من فن التطريز الشاوي الأصيل.",
      fr: "Les motifs croisés s'inspirent de l'art de la broderie chaoui authentique.",
      en: "The cross motifs draw on authentic Chaoui embroidery art.",
    },
    occasion: {
      ar: "الاستخدام اليومي والمناسبات",
      fr: "Usage quotidien et occasions",
      en: "Daily wear and occasions",
    },
    artisan_name: null,
    price_dzd: 2500,
    sizes: null,
    images: ["/products/4.webp"],
    in_stock: true,
    featured: false,
    created_at: now,
  },
  {
    id: "fb-11",
    slug: "fustan-chaoui-embroidered",
    category: "heritage",
    title: {
      ar: "فستان شاوي مطرز",
      fr: "Robe chaoui brodée",
      en: "Embroidered Chaoui Dress",
    },
    short_description: {
      ar: "فستان طويل أسود مطرز بنقوش حمراء وبرتقالية على الصدر والأكمام والأطراف، مع حزام مطرز.",
      fr: "Robe longue noire brodée de motifs rouge et orange au plastron, aux manches et aux ourlets, avec une ceinture brodée.",
      en: "Long black dress embroidered with red and orange motifs on the bodice, sleeves and hems, with an embroidered belt.",
    },
    story: {
      ar: "فستان واسع بقصّة تقليدية، مطرّز يدويًا بنقوش هندسية على الصدر والأكمام والذيل، مع حزام مطرّز يبرز الخصر.",
      fr: "Robe ample à la coupe traditionnelle, brodée à la main de motifs géométriques au plastron, aux manches et au bas, avec une ceinture brodée qui souligne la taille.",
      en: "A flowing dress with a traditional cut, hand-embroidered with geometric motifs on the bodice, sleeves and hem, with an embroidered belt that defines the waist.",
    },
    symbolism: {
      ar: "النقوش الهندسية الحمراء ترمز للحياة والخصوبة في التراث الأوراسي.",
      fr: "Les motifs géométriques rouges symbolisent la vie et la fertilité dans le patrimoine des Aurès.",
      en: "The red geometric motifs symbolize life and fertility in Aurès heritage.",
    },
    occasion: {
      ar: "المناسبات والاحتفالات",
      fr: "Occasions et célébrations",
      en: "Occasions and celebrations",
    },
    artisan_name: null,
    price_dzd: 12000,
    sizes: ["S", "M", "L", "XL"],
    images: ["/products/5.webp"],
    in_stock: true,
    featured: false,
    created_at: now,
  },
  {
    id: "fb-12",
    slug: "bernous-chaoui-embroidered",
    category: "heritage",
    title: {
      ar: "برنوس شاوي مطرز",
      fr: "Burnous chaoui brodé",
      en: "Embroidered Chaoui Burnous",
    },
    short_description: {
      ar: "برنوس رمادي بقبّعة، مطرز بنقوش معيّنية ملوّنة وحواف بألوان التراث وشرّابات.",
      fr: "Burnous gris à capuche, brodé de motifs en losange colorés, avec bordures aux couleurs du patrimoine et pompons.",
      en: "Grey hooded burnous, embroidered with colorful diamond motifs, with heritage-colored trims and tassels.",
    },
    story: {
      ar: "برنوس واسع من قماش رمادي بقبّعة، مزيّن بنقوش معيّنية ملوّنة على الظهر والحواف، مع شرّابات يدوية على الأطراف.",
      fr: "Burnous ample en tissu gris à capuche, orné de motifs en losange colorés au dos et sur les bords, avec des pompons faits main.",
      en: "A wide grey-fabric hooded burnous, adorned with colorful diamond motifs on the back and edges, with handmade tassels along the trims.",
    },
    symbolism: {
      ar: "المعيّن رمز للخصوبة والحماية في الزخرفة الأمازيغية.",
      fr: "Le losange est un symbole de fertilité et de protection dans l'ornement amazigh.",
      en: "The diamond is a symbol of fertility and protection in Amazigh ornamentation.",
    },
    occasion: {
      ar: "المناسبات والطقس البارد",
      fr: "Occasions et temps frais",
      en: "Occasions and cooler weather",
    },
    artisan_name: null,
    price_dzd: 14000,
    sizes: null,
    images: ["/products/6.webp"],
    in_stock: true,
    featured: false,
    created_at: now,
  },
];

export const fallbackArchive: ArchiveItem[] = [
  {
    id: "fa-photo-celebration",
    slug: "photo-aures-celebration",
    kind: "photo",
    title: {
      ar: "احتفال تقليدي في الأوراس",
      fr: "Célébration traditionnelle dans les Aurès",
      en: "Traditional celebration in the Aurès",
    },
    description: {
      ar: "نساء بالزيّ الشاوي التقليدي يؤدّين رقصة احتفالية بين الجبال، مشهد يجسّد حيوية التراث الأوراسي.",
      fr: "Des femmes en tenue chaoui traditionnelle exécutent une danse de fête au milieu des montagnes, une scène qui incarne la vitalité du patrimoine des Aurès.",
      en: "Women in traditional Chaoui dress perform a festive dance amid the mountains, a scene that embodies the vitality of Aurès heritage.",
    },
    year: null,
    media_url: "/products/11.webp",
    created_at: now,
  },
  {
    id: "fa-photo-women",
    slug: "photo-aures-women-costume",
    kind: "photo",
    title: {
      ar: "نساء أوراسيات بالزيّ التقليدي",
      fr: "Femmes aurassiennes en costume traditionnel",
      en: "Aurès women in traditional costume",
    },
    description: {
      ar: "صورة توثيقية لامرأة وفتاة بالزيّ الأوراسي الكامل، بالحلي الفضية والعمامة الملوّنة والمنسوجات التقليدية.",
      fr: "Photographie documentaire d'une femme et d'une fille en costume aurassien complet, avec bijoux d'argent, turban coloré et textiles traditionnels.",
      en: "A documentary photograph of a woman and a girl in full Aurès costume, with silver jewelry, a colorful turban and traditional textiles.",
    },
    year: null,
    media_url: "/products/12.webp",
    created_at: now,
  },
  {
    id: "fa-1",
    slug: "timeline-1900-melhfa",
    kind: "timeline",
    title: {
      ar: "الملحفة في بدايات القرن العشرين",
      fr: "La melhfa au début du XXe siècle",
      en: "The melhfa in the early 20th century",
    },
    description: {
      ar: "كانت الملحفة قطعة محورية في الزيّ النسائي، تُنسج محليًا وتعكس الانتماء القبلي.",
      fr: "La melhfa était une pièce centrale du costume féminin, tissée localement et reflétant l'appartenance tribale.",
      en: "The melhfa was a central piece of women's dress, locally woven and reflecting tribal belonging.",
    },
    year: 1900,
    media_url: archiveImages.woman_hillside,
    created_at: now,
  },
  {
    id: "fa-2",
    slug: "symbol-color-red",
    kind: "symbol",
    title: {
      ar: "رمزية اللون الأحمر",
      fr: "Symbolique du rouge",
      en: "Symbolism of red",
    },
    description: {
      ar: "الأحمر في اللباس الأوراسي يرمز للحياة، الخصوبة، والحماية من العين.",
      fr: "Le rouge dans le costume aurassien symbolise la vie, la fertilité et la protection contre le mauvais œil.",
      en: "Red in the Aurès costume symbolizes life, fertility, and protection from the evil eye.",
    },
    year: null,
    media_url: archiveImages.village_textiles,
    created_at: now,
  },
  {
    id: "fa-3",
    slug: "interview-fatima-zahra",
    kind: "interview",
    title: {
      ar: "مقابلة: فاطمة الزهراء — حرفية النسيج",
      fr: "Entretien : Fatima Zahra, artisane tisseuse",
      en: "Interview: Fatima Zahra, weaver",
    },
    description: {
      ar: "تروي فاطمة الزهراء كيف تعلمت النسيج من جدّتها، وكيف تنقل المعرفة اليوم لبناتها.",
      fr: "Fatima Zahra raconte comment elle a appris le tissage de sa grand-mère, et comment elle transmet aujourd'hui ce savoir à ses filles.",
      en: "Fatima Zahra recounts learning weaving from her grandmother and passing the knowledge on to her daughters.",
    },
    year: null,
    media_url: archiveImages.woman_desert,
    created_at: now,
  },
];

export const fallbackArtisans: Artisan[] = [
  {
    id: "art-1",
    name: "فاطمة الزهراء",
    bio: {
      ar: "حرفية نسيج بخبرة 25 سنة، متخصصة في الملحفة الأوراسية التقليدية.",
      fr: "Tisseuse de 25 ans d'expérience, spécialisée dans la melhfa aurassienne.",
      en: "Weaver with 25 years experience, specialized in the Aurès melhfa.",
    },
    village: "مشونش",
    years_experience: 25,
    photo_url: null,
    created_at: now,
  },
  {
    id: "art-2",
    name: "خديجة بن صالح",
    bio: {
      ar: "حرفية تطريز ومصممة، تجمع بين الأصالة والتصميم المعاصر.",
      fr: "Brodeuse et designer, combinant authenticité et design contemporain.",
      en: "Embroiderer and designer combining authenticity with contemporary design.",
    },
    village: "مشونش",
    years_experience: 18,
    photo_url: null,
    created_at: now,
  },
];

export const fallbackPosts: BlogPost[] = [
  {
    id: "p-ar",
    slug: "introducing-anamil",
    locale: "ar",
    title: "مرحبًا بكم في أنامل الأوراس والزيبان",
    excerpt: "لماذا أنشأنا هذه المنصة، وما الذي يميزها عن متجر تقليدي.",
    body: "هذا المشروع ليس متجرًا فقط. هو محاولة لإنقاذ تراثٍ يتلاشى، وتمكين نساء يصنعنه بأيديهن.\n\nنبدأ ببسكرة، بمنطقة مشونش، ثم نتوسع.",
    cover_image: null,
    reading_minutes: 4,
    published_at: now,
    created_at: now,
  },
  {
    id: "p-fr",
    slug: "introducing-anamil",
    locale: "fr",
    title: "Bienvenue chez Anamil El Aouras Wa El Zibane",
    excerpt:
      "Pourquoi nous avons créé cette plateforme, et ce qui la distingue d'une boutique classique.",
    body: "Ce projet n'est pas qu'une boutique. C'est une tentative de sauver un patrimoine qui s'efface et d'émanciper des femmes qui le créent de leurs mains.\n\nNous commençons à Biskra, dans la région de Mchounèche, puis nous élargirons.",
    cover_image: null,
    reading_minutes: 4,
    published_at: now,
    created_at: now,
  },
  {
    id: "p-en",
    slug: "introducing-anamil",
    locale: "en",
    title: "Welcome to Anamil El Aouras Wa El Zibane",
    excerpt:
      "Why we built this platform and what sets it apart from a regular store.",
    body: "This project is not just a store. It is an attempt to save a fading heritage and empower the women who make it with their hands.\n\nWe begin in Biskra, in the Mchounèche region, and will expand from there.",
    cover_image: null,
    reading_minutes: 4,
    published_at: now,
    created_at: now,
  },
];
